'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {main}=require('../bin/opencode-termux');
function layout(root){const prefix=path.join(root,'prefix'),pkg=path.join(prefix,'lib/node_modules/@bash0816/opencode-termux');fs.mkdirSync(path.join(pkg,'lib'),{recursive:true});return {prefix,pkg,lib:path.join(pkg,'lib')};}
async function invoke(args,over={}) {
 const state={setup:0,upstream:0,npm:0,registry:0,fs:0,updates:0,out:'',codes:[],argv:null,env:null};
 const root=fs.mkdtempSync(path.join(process.cwd(),'.tmp-bin-'));const paths=layout(root);state.prefix=paths.prefix;
 try {
  await main({args,packageRoot:over.packageRoot||paths.pkg,libPath:over.libPath||paths.lib,env:over.env||{PATH:'/x'},glibcLibDir:'/glibc',
   setup:async(...a)=>{state.setup++;return over.setup?over.setup(...a):'/cache';},
   execFileSync:(...a)=>{state.upstream++;state.argv=a[1];state.env=a[2].env;if(over.execFileSync)return over.execFileSync(...a);},
   registryGet:async(...a)=>{state.registry++;if(over.registryGet)return over.registryGet(...a);state.request=a;return {statusCode:200,body:'{"version":"99.99.99"}'};},
   spawnSync:(...a)=>{state.npm++;state.npmArgs=a;return over.spawnSync?over.spawnSync(...a):{status:0};},
   write:x=>state.out+=x,exit:c=>state.codes.push(c),fs:{realpathSync:p=>{state.fs++;return fs.realpathSync(p);}}
  });return {state,paths};
 } finally {fs.rmSync(root,{recursive:true,force:true});}
}
test('real update flow runs wrapper update; invalid arguments and help stop before side effects',async()=>{
 let {state}=await invoke(['update']);assert.deepEqual(state.codes,[0]);assert.deepEqual([state.setup,state.upstream,state.registry,state.npm],[0,0,1,1]);assert.deepEqual(state.npmArgs[1].slice(0,4),['install','-g','--prefix',state.prefix]);
 for(const command of ['update','upgrade']){
  for(const args of [[command,'--help=x'],[command,'--help','bad'],[command,'1.2.3','-h'],[command,'--help','-h'],[command,'bad']]){
   ({state}=await invoke(args));assert.deepEqual(state.codes,[2],args.join(' '));assert.deepEqual([state.fs,state.setup,state.upstream,state.registry,state.npm],[0,0,0,0,0],args.join(' '));
  }
  for(const args of [[command,'--help'],[command,'-h']]){
   ({state}=await invoke(args));assert.deepEqual(state.codes,[0],args.join(' '));assert.deepEqual([state.fs,state.setup,state.upstream,state.registry,state.npm],[0,0,0,0,0],args.join(' '));
  }
 }
 for(const args of [['uninstall'],['uninstall','--help','anything']]){({state}=await invoke(args));assert.deepEqual(state.codes,[1]);assert.match(state.out,/opencode debug paths/);assert.match(state.out,/削除前に/);assert.deepEqual([state.setup,state.upstream,state.registry,state.npm],[0,0,0,0]);}
});
test('real bin update accepts a bin/package symlink resolving to the standard prefix',async()=>{const root=fs.mkdtempSync(path.join(process.cwd(),'.tmp-bin-symlink-'));try{const target=layout(root),binLink=path.join(root,'opencode-link');fs.symlinkSync(path.resolve('bin/opencode-termux'),binLink);const pkgLink=path.join(root,'package-link');fs.symlinkSync(target.pkg,pkgLink,'dir');assert.equal(fs.realpathSync(binLink),path.resolve('bin/opencode-termux'));const {state}=await invoke(['update'],{packageRoot:pkgLink,libPath:path.join(pkgLink,'lib')});assert.deepEqual(state.codes,[0]);assert.deepEqual([state.setup,state.upstream,state.registry,state.npm],[0,0,1,1]);assert.deepEqual(state.npmArgs[1].slice(0,4),['install','-g','--prefix',target.prefix]);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('real bin update reports registry 404 with exit 1 and never runs npm',async()=>{const {state}=await invoke(['update'],{registryGet:async()=>{return {statusCode:404,body:'{}'};}});assert.deepEqual(state.codes,[1]);assert.deepEqual([state.setup,state.upstream,state.registry,state.npm],[0,0,1,0]);});
test('real bin update stops on prefix mismatch before registry and npm',async()=>{let state;const root=fs.mkdtempSync(path.join(process.cwd(),'.tmp-bin-mismatch-'));const A=layout(root),B=layout(path.join(root,'other')); try{const mismatch=await invoke(['update'],{packageRoot:A.pkg,libPath:B.lib});state=mismatch.state;assert.deepEqual(state.codes,[1]);assert.deepEqual([state.setup,state.upstream,state.registry,state.npm],[0,0,0,0]);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('ordinary command preserves argv and environment defaults only unset autoupdate variable',async()=>{let {state}=await invoke(['models','--json']);assert.deepEqual(state.codes,[]);assert.equal(state.setup,1);assert.equal(state.upstream,1);assert.deepEqual(state.argv,['models','--json']);assert.equal(state.env.OPENCODE_DISABLE_AUTOUPDATE,'1');assert.equal(state.env.LD_PRELOAD,'');assert.equal(state.env.LD_LIBRARY_PATH,'/glibc');for(const value of ['0','false','']){({state}=await invoke(['models'],{env:{OPENCODE_DISABLE_AUTOUPDATE:value}}));assert.equal(state.env.OPENCODE_DISABLE_AUTOUPDATE,value);}});
test('setup failure exits 1 without upstream execution',async()=>{const {state}=await invoke(['models'],{setup:async()=>{throw Error('no')}});assert.deepEqual(state.codes,[1]);assert.equal(state.upstream,0);});

test('child process through real bin symlink runs update for the expected prefix',()=>{
 const cp=require('node:child_process'),os=require('node:os');const root=fs.mkdtempSync(path.join(process.cwd(),'.tmp-real-bin-'));try{const prefix=path.join(root,'prefix'),pkg=path.join(prefix,'lib/node_modules/@bash0816/opencode-termux');fs.mkdirSync(path.join(pkg,'bin'),{recursive:true});fs.mkdirSync(path.join(pkg,'lib'),{recursive:true});fs.mkdirSync(path.join(pkg,'config'),{recursive:true});for(const f of ['bin/opencode-termux','lib/argv-route.js','lib/self-update.js','lib/setup.js','lib/patcher.js','lib/downloader.js','lib/version-utils.js','package.json']){const dest=path.join(pkg,f);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.resolve(f),dest);}const link=path.join(prefix,'bin/opencode');fs.mkdirSync(path.dirname(link),{recursive:true});fs.symlinkSync(path.join(pkg,'bin/opencode-termux'),link);
 const preload=path.join(root,'transport.js'),npmDir=path.join(root,'npm-bin'),record=path.join(root,'npm-record');fs.mkdirSync(npmDir);fs.writeFileSync(preload,`const https=require('https'),{EventEmitter}=require('events');https.get=(url,cb)=>{process.env.REGISTRY_URL=url;const req=new EventEmitter();req.destroy=()=>req.emit('error',new Error('destroyed'));process.nextTick(()=>{const res=Object.assign(new EventEmitter(),{statusCode:200});cb(res);res.emit('data',Buffer.from('{"version":"99.99.99"}'));res.emit('end');});return req;};`);const npm=path.join(npmDir,'npm');fs.writeFileSync(npm,`#!${process.execPath}\nrequire('node:fs').appendFileSync(process.env.RECORD_FILE,process.argv.slice(2).join(' ')+'\\n');\n`);fs.chmodSync(npm,0o755);
 const env={...process.env,PATH:npmDir+path.delimiter+process.env.PATH,NODE_OPTIONS:`--require=${preload}`,RECORD_FILE:record};const result=cp.spawnSync(link,['update'],{encoding:'utf8',env});assert.equal(result.status,0,result.stderr);assert.equal(fs.readFileSync(record,'utf8').trim(),`install -g --prefix ${prefix} @bash0816/opencode-termux@99.99.99`);assert.equal(result.stderr.includes('Could not detect'),false);
 }finally{fs.rmSync(root,{recursive:true,force:true});}});
test('child process refuses bad layouts without attempting network or npm',()=>{
 const cp=require('node:child_process');const root=fs.mkdtempSync(path.join(process.cwd(),'.tmp-real-bin-reject-'));try{const mk=(p)=>{const pkg=path.join(p,'lib/node_modules/@bash0816/opencode-termux');fs.mkdirSync(path.join(pkg,'bin'),{recursive:true});fs.mkdirSync(path.join(pkg,'lib'),{recursive:true});for(const f of ['bin/opencode-termux','lib/argv-route.js','lib/self-update.js','lib/setup.js','lib/patcher.js','lib/downloader.js','lib/version-utils.js','package.json']){const d=path.join(pkg,f);fs.mkdirSync(path.dirname(d),{recursive:true});fs.copyFileSync(path.resolve(f),d);}return pkg;};const a=mk(path.join(root,'A')),b=mk(path.join(root,'B'));const cases=[];const bin=(pkg,name)=>{const p=path.join(root,'A','bin',name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.symlinkSync(path.join(pkg,'bin/opencode-termux'),p);return p;};fs.rmSync(path.join(a,'lib'),{recursive:true,force:true});fs.symlinkSync(path.join(b,'lib'),path.join(a,'lib'),'dir');cases.push(bin(a,'lib-mismatch'));const odd=path.join(root,'odd');fs.mkdirSync(path.join(odd,'lib'),{recursive:true});for(const f of ['bin/opencode-termux','lib/argv-route.js','lib/self-update.js','lib/setup.js','lib/patcher.js','lib/downloader.js','lib/version-utils.js','package.json']){const d=path.join(odd,f);fs.mkdirSync(path.dirname(d),{recursive:true});fs.copyFileSync(path.resolve(f),d);}cases.push(path.join(odd,'bin/opencode-termux'));
 const preload=path.join(root,'network-guard.cjs'),networkRecord=path.join(root,'network-record'),npmRecord=path.join(root,'npm-record');
 fs.writeFileSync(preload,`const fs=require('node:fs');const mark=(name)=>{try{fs.appendFileSync(process.env.NETWORK_RECORD,name+'\\n')}catch{};throw new Error('network forbidden: '+name)};for(const [m,n] of [['https','get'],['https','request'],['http','get'],['http','request'],['net','connect'],['tls','connect'],['dns','lookup']]){const o=require(m);o[n]=(...a)=>mark(m+'.'+n)};`);
 const npmDir=path.join(root,'npm-bin');fs.mkdirSync(npmDir);const npm=path.join(npmDir,'npm');fs.writeFileSync(npm,`#!${process.execPath}\nrequire('node:fs').appendFileSync(process.env.NPM_RECORD,'called\\n');\n`);fs.chmodSync(npm,0o755);const probe=cp.spawnSync(npm,['--probe'],{encoding:'utf8',env:{...process.env,NPM_RECORD:npmRecord}});assert.equal(probe.status,0,probe.stderr);assert.equal(fs.readFileSync(npmRecord,'utf8'),'called\n','fake npm probe was not recorded');fs.rmSync(npmRecord);
 for(const exe of cases){const r=cp.spawnSync(exe,['update'],{encoding:'utf8',env:{...process.env,PATH:npmDir+path.delimiter+process.env.PATH,NODE_OPTIONS:`--require=${preload}`,NETWORK_RECORD:networkRecord,NPM_RECORD:npmRecord}});assert.equal(r.status,1,`${exe}: ${r.stderr}`);assert.match(r.stderr,/Could not detect the installation prefix/);assert.equal(fs.existsSync(networkRecord),false,'network guard was not invoked');assert.equal(fs.existsSync(npmRecord),false,'npm was not invoked');}
 }finally{fs.rmSync(root,{recursive:true,force:true});}});

test('all non-leading management words pass unchanged to upstream',async()=>{
 for(const args of [[],['--help'],['-h'],['--version','update'],['--version=true','update'],['--version=false','update'],['--completions','bash','upgrade'],['--completions=bash','upgrade'],['--no-print-logs','plugin','update','--help'],['--no-print-logs=true','update'],['--no-print-logs=false','update'],['--print-logs','plugin','update'],['--print-logs','run','uninstall'],['run','update','the docs']]){
  const {state}=await invoke(args);assert.deepEqual([state.setup,state.upstream,state.registry,state.npm],[1,1,0,0],args.join(' '));assert.deepEqual(state.argv,args,args.join(' '));
 }
});
